config/routes.rb
Rails.application.routes.draw do
  root to: 'statics#home'

  resources :tags do
    collection do
      get :id_from_code
    end
  end

  devise_for :volunteers
  devise_for :drivers
  resources :drivers do
    collection do
      get :notify
      get :send_text_message   
      put :accept
    end
  end
  resources :volunteers do 
    collection do
      put :check_delivered
      put :check_undelivered
    end 
  end

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates_presence_of :name, :age

  belongs_to :driver
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if resource.class == Driver
      drivers_path
    elsif resource.class == Volunteer
      tags_path
    end
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  def index

  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :authenticate_driver!, only: :index

	def index
		if current_driver
			@tags = Array.new
			Tag.find_each do |t|
				if t.status == "Requested"
					l1 = parse_location(t.location)
					l2 = parse_location(current_driver.location)
					if haversine_distance(l1[0], l1[1], l2[0], l2[1]) < 5
						@tags << t
					end
				end
			end	
		end
	end

	def accept
		tag = Tag.find(params[:id])
		tag.status = "Accepted"
		tag.driver = current_driver
		tag.save

		message = "Your request has been accepted. " + current_driver.name.to_s + " is on the way!"

		send_text_message([tag.phone], message)

		render nothing: true
	end

	def notify
		tag = Tag.find(params[:id])
		dl = params[:location]
		dp = params[:phone]
		tag.location = dl
		tag.phone = dp
		tag.status = "Requested"
		tag.save
		
		numbers = []
		#send_text_message
		Driver.all.each do |d|
			if d.location?
				loc = parse_location(d.location)
				donorLoc = parse_location(dl)
				miles = haversine_distance(loc[0], loc[1], donorLoc[0], donorLoc[1])
				if (miles < 5)
					numbers << d.phone
					puts d.phone
				end
			end
		end

		message = "Hello - a present delivery has been requested. Please click the following link to view the request: " + drivers_url

		send_text_message(numbers, message)

		render nothing: true
	end

	def send_text_message(numbers, message)
		@twilio_client = Twilio::REST::Client.new ENV["TWILIO_SID"], ENV["TWILIO_TOKEN"]

		for num in numbers
			@twilio_client.account.sms.messages.create(
				:from => "+1#{ENV['TWILIO_PHONE_NUMBER']}",
				:to => "+1" + num,
				:body => message
			)
		end
	end

	def parse_location(st)
		arr = []
		result = st.split(',')
		arr[0] = result[0].strip.to_f
		arr[1] = result[1].strip.to_f
		return arr
	end

	def haversine_distance( lat1, lon1, lat2, lon2 )
		max_distance_away_in_km = 100.0
		rad_per_deg             = 0.017453293

		rmiles  = 3956           # radius of the great circle in miles
		rkm     = 6371           # radius in kilometers, some algorithms use 6367
		rfeet   = rmiles * 5282  # radius in feet
		rmeters = rkm * 1000     # radius in meters
		dlon = lon2 - lon1
		dlat = lat2 - lat1

		dlon_rad = dlon * rad_per_deg
		dlat_rad = dlat * rad_per_deg

		lat1_rad = lat1 * rad_per_deg
		lon1_rad = lon1 * rad_per_deg

		lat2_rad = lat2 * rad_per_deg
		lon2_rad = lon2 * rad_per_deg

		a = (Math.sin(dlat_rad/2))**2 + Math.cos(lat1_rad) *
		Math.cos(lat2_rad) * (Math.sin(dlon_rad/2))**2
		c = 2 * Math.atan2( Math.sqrt(a), Math.sqrt(1-a))

	  dmi     = rmiles * c      # delta between the two points in miles
	  dkm     = rkm * c         # delta in kilometers
	  dfeet   = nil #rfeet * c       # delta in feet
	  dmeters = nil #rmeters * c     # delta in meters

	  return dmi
	end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
    if current_driver
      redirect_to drivers_path
    elsif current_volunteer
      redirect_to tags_path
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_volunteer!, only: :index
  def index 
    @tags = Tag.all
  end

  def show 
    @tag = Tag.find_by_code!(params[:id])
  end

  def id_from_code
    render json: Tag.find_by_code(params[:code]).id
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :age, :gender, :wish, :alternative_wish, :status, :zone, :code)
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def check_delivered
    @tag = Tag.find(params[:id])
    @tag.status = "Delivered"
    @tag.zone = 023
    @tag.save

    Pusher['volunteer_channel'].trigger('deliver', {
      message: 'Present delivered!'
    })

    render nothing: true
  end

  def check_undelivered
    @tag = Tag.find(params[:id])
    @tag.status = "Unbought"
    @tag.save

    render nothing: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/donors/show.html.haml
%button.notify hello this is andrew

%p#loctext
= javascript_include_tag("donor")

app/views/drivers/index.html.haml
.container
  .header
    %ul.nav.nav-pills.pull-right
      %li
        %a{:href => "/"} Donor
      %li.active
        %a{:href => "/drivers"} Driver
      %li
        %a{:href => "/tags"} Volunteer
      %li
        = link_to('Logout', destroy_driver_session_path, :method => :delete)
    %h3.text-muted Santa

    .centrax
      - if @tags.empty?
        %h2 No Delivery Requests
      - else
        %h2 We've found a job!
        %p Donor number: #{@tags[0].phone}
        .btn.btn-primary{onclick: "accept()"} Accept? 
        %br
        %br
        %br
      = image_tag("box.svg", :style => "width:150px")
        
    - if !@tags.empty?
      = javascript_tag do
        id = "#{j @tags[0].id.to_s}";
        loc = "#{j @tags[0].location.to_s}";
    = javascript_include_tag "tag"

app/views/drivers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/show.html.haml
hello this is andrew

%p#loctext
= javascript_include_tag("home")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Santa
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  - flash.each do |name, msg|
    = content_tag :div, msg, :id => name, class: "alert alert-info" 

  %body
    = yield

app/views/statics/home.html.haml
.container
  .header
    %ul.nav.nav-pills.pull-right
      %li.active
        %a{:href => "/"} Donor
      %li
        %a{:href => "/drivers"} Driver
      %li
        %a{:href => "/tags"} Volunteer
    %h3.text-muted Santa
  .jumbotron{:style => "margin-top:60px"}
    .row
      .col-md-5
        = image_tag("santacrew.png", :style => "width:100%")
      .col-md-7
        %h1 Christmas for All
        %p.lead Family Giving Tree makes kids' dreams come true, one gift at a time. We make the process of delivering gifts simple and easy.

        If you're a donor, enter the code on your gift tag below or scan the QR code.
    .row{:style => "margin-top:50px"}
      .col-md-8
        %input#donor_info.form-control{:style => "background-image: none; background-position: 0% 0%; background-repeat: repeat;", :type => "text", :placeholder => "Enter Gift Code", :style => "height:64px"}/
      .col-md-4
        %p
          %a#donor.btn.btn-lg.btn-success{:role => "button"} Submit Gift Code

- if Rails.env.production?
  = javascript_tag do
    url = "#{j "http://santa-giving-tree.herokuapp.com/tags/"}";
- else
  = javascript_tag do
    url = "#{j "http://localhost:3000/tags/"}";
= javascript_include_tag "home"

app/views/tags/index.haml
%head
  %script{:src => "//js.pusher.com/2.2/pusher.min.js", :type => "text/javascript"}

.container
  .header
    %ul.nav.nav-pills.pull-right
      %li
        %a{id: 'donor', :href => "#"} Donor
      %li
        %a{:href => "/drivers"} Driver
      %li.active
        %a{:href => "/tags"} Volunteer
      %li
        = link_to('Logout', destroy_volunteer_session_path, :method => :delete)
    %h3.text-muted Santa
  %table.table.table-striped.table-hover{:style => "margin-top:40px"}
    %thead
      %tr
        %th Code
        %th Name
        %th Wish
        %th Status
    %tbody
      - @tags.each do |tag|
        %tr
          %td #{tag.id}
          %td #{tag.name}
          %td #{tag.wish}
          %td #{tag.status}

= javascript_include_tag("pusher")

app/views/tags/show.haml
%head
  %script{:src => "//js.pusher.com/2.2/pusher.min.js", :type => "text/javascript"}

= stylesheet_link_tag("tags")
.topborder
.container
  .central
    = image_tag("gift.gif", :class => "gift")
    %h3.recipient
      = @tag.name + "'s Gift"
    %h5.wish
      %span.quoter{:style => (@tag.wish.nil? ? "display:none" : "")} &ldquo;
      = @tag.wish
    #qrcode

    - if !current_volunteer
      .small-contain{:style => "width:500px; margin:50px auto; display:block"}
        .row
          .col-md-6
            %input.form-control#donor_phone{placeholder: "Your Phone Number"}
          .col-md-6
            .btn.btn-primary.notify{:style => "width:100%;"} Request a Driver
      %p#loctext{:style => "display:none"}
    - else 
      .small-contain{:style => "width:500px; margin:50px auto; display:block; text-align:center"}
        %p Zone: #{@tag.zone}
        - if @tag.status != "Delivered"
          .btn.btn-primary#deliver{:style => "width:80%;"} Check as Delivered
        - else 
          .btn.btn-primary#undeliver{:style => "width:80%;"} Check as Not Delivered
  
  .load
    %h2.loadtext Searching for drivers...
    .loader
      .sphere.s-gold
      .sphere.s-5
      .sphere.s-4
      .sphere.s-3
      .sphere.s-2
      .sphere.s-1
    .loader-faster
      .sphere.s-gold
      .sphere.s-5
      .sphere.s-4
      .sphere.s-3
      .sphere.s-2
      .sphere.s-1

= javascript_tag do
  code = "#{j @tag.code.to_s}";
  id = "#{j @tag.id.to_s}";
= javascript_include_tag("donor")
= javascript_include_tag("qrcode.min")
= javascript_include_tag("qr")
= javascript_include_tag("pusher")